### ISSUE TITLE
Duplicate functions cause unrecoverable error when creating function map

### ISSUE THREAD

**Issue by willkroboth** [willkroboth/ConfigCommands#3]
# Problem:
When two Definitions with the same name and parameters are added to a FunctionList, they clash when being converted to a map, throwing an error like so:
```
[16:21:38 INFO]: [ConfigCommands] Initializing function maps
[16:21:38 INFO]: [ConfigCommands] 	InternalArrayListArgument
[16:21:38 INFO]: [ConfigCommands] 	InternalStringArgument
[16:21:38 INFO]: [ConfigCommands] 	InternalBooleanArgument
[16:21:38 INFO]: [ConfigCommands] 	InternalIntegerArgument
[16:21:38 ERROR]: [ConfigCommands] 	Unexpected fatal exception when setting function map for InternalIntegerArgument
[16:21:38 ERROR]: Error occurred while enabling ConfigCommands v1.0.0 (Is it up to date?)
java.lang.IllegalArgumentException: duplicate key: Definition{name='', parameters=[]}
	at java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:1189) ~[?:?]
	at java.util.Map.ofEntries(Map.java:1668) ~[?:?]
	at me.willkroboth.ConfigCommands.InternalArguments.InternalArgument.createFunctionMaps(InternalArgument.java:305) ~[ConfigCommands.jar:?]
	at me.willkroboth.ConfigCommands.ConfigCommands.onEnable(ConfigCommands.java:95) ~[ConfigCommands.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-283]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:21:38 INFO]: [ConfigCommands] Disabling ConfigCommands v1.0.0
```
Currently, errors like this interrupt the command registering process completely. 

# Solution:
This problem can be worked around by making sure a duplicate Definition is never used, but that may not be easily possible if two separate AddOns have FunctionAdders for the same class. An easy fix to avoid this problem is to convert FunctionList to a FunctionSet, and resolve conflicts by choosing the function added to the set latest.

**Comment by willkroboth** [comment]
Resolved in v 2.0.0
